language: node_js

node_js:
  - node

matrix:
  include:
    #
    # Build using whatever is default on all platforms:
    #
    #   https://docs.travis-ci.com/user/reference/linux/
    #   https://docs.travis-ci.com/user/reference/osx/
    #   https://docs.travis-ci.com/user/reference/windows/
    #
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
    - os: linux
      dist: precise
    - os: linux
      arch: arm64
    - os: osx
      osx_image: xcode11.3
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode9.4
    - os: osx
      osx_image: xcode8.3
    - os: osx
      osx_image: xcode7.3
    - os: osx
      osx_image: xcode6.4
    - os: windows
    # Build latest node and historical LTS releases on Linux/amd64 only.
    - os: linux
      node_js: "13"
    - os: linux
      node_js: "10"
    - os: linux
      node_js: "8"
    - os: linux
      node_js: "6"
    - os: linux
      node_js: "4"
    - os: linux
      node_js: "0.12"
    - os: linux
      node_js: "0.10"
