language: node_js
matrix:
  include:
    - os: linux
      node_js: "13"
    - os: linux
      node_js: "12"
    - os: linux
      node_js: "0.10"
    - os: linux
      node_js: "0.8"
    - os: osx
      node_js: "13"
    - os: windows
      node_js: "13"
